### ISSUE TITLE
Codes about iamge enhancement

### ISSUE THREAD

**Issue by xuhui1994** [swz30/MIRNet#11]
Thank you for your excellent work about image filed firstly? In this repo， only train_denosing.py can be seen . Could you provide image enhancement  training .py code? Looking forward to your reply.

**Comment by swz30** [comment]
Train_denoising.py file is provided as an example. You can use the same training code for image enhancement as well. Just provide the paths to your training and validation data here https://github.com/swz30/MIRNet/blob/d7e471704fcdb67526af027352c1a5ea4619ee00/training.yml#L23

**Comment by swz30** [comment]
Please set `NUM_EPOCHS` to 200 for Image Enhancement training.
