### ISSUE TITLE
Where can I get validation images of SIDD?

### ISSUE THREAD

**Issue by ljpadam** [swz30/MIRNet#12]
Where can I get validation image of SIDD? Do you use the same script to extract patches for training and validataion images?

**Comment by adityac8** [comment]
HI @ljpadam 
The `mat` files for the validation data of the SIDD dataset can be downloaded from [here](https://www.eecs.yorku.ca/~kamel/sidd/dataset.php).
We extract the patches and save them in `png` format, which are available [here](https://drive.google.com/drive/folders/1j5ESMU0HJGD-wU6qbEdnt569z7sM3479?usp=sharing).

Thanks
