### ISSUE TITLE
Maybe the checkpoints of enhancemenet on LOL datasets is wrong?

### ISSUE THREAD

**Issue by peachis** [swz30/MIRNet#15]
Your work is very productive, but I found that when reproducing the SSIM and PSNR metrics on the LOL dataset, the enhanced results obtained with the [checkpoints ](https://drive.google.com/file/d/1t_FcBuMZD5th2KWVVNXYGJ7bMz5ZAWvF/view?usp=sharing) you provided were different from [here's](https://drive.google.com/drive/folders/1TbMyf8hRX-MMQ3m95Yowxho77exvwmUd?usp=sharing) and the scores were a bit worse.
I wonder if there is any step I did wrong?

**Comment by swz30** [comment]
Hi @peachis 

Could you please provide the SSIM/PSNR scores that you are getting with the checkpoints?

**Comment by peachis** [comment]
Hi @swz30, I got PSNR: 21.2725, SSIM: 0.8165 with code:

from skimage.measure import compare_ssim, compare_psnr
...
ssim = compare_ssim(rgb_in, rgb_gt, data_range=255, multichannel =True)
psnr = compare_psnr(rgb_in, rgb_gt, data_range=255 )
...

**Comment by swz30** [comment]
@peachis We use MATLAB to compute PSNR/SSIM scores. The SSIM implementation is provided [here](https://ece.uwaterloo.ca/~z70wang/research/ssim/).

**Comment by peachis** [comment]
@swz30 Thank you for providing details.
The PSNR/SSIM obtained with the images you provided is 24.1011/0.8421 (use skimage.measure), which is similar to the result you mentioned.
While the images enhanced with your checkpoint can only get 21.2725/0.8165.
I compared the images you provided with the one enhanced with checkpoint and found that they are indeed different. Maybe I missed some steps?

**Comment by swz30** [comment]
We just checked on our end, and I confirm that the numbers (24.14 PSNR) are reproducible using pre-trained weights. We checked with both the MATLAB and `skimage==0.16.2`.

**Comment by peachis** [comment]
@swz30 Thanks a lot!
Finally, I find the difference.
I clone your code before long in 2020.08, and the images loading by `img = lycon.load(filepath)`. I'm not familiar with lycon and just change it to `cv2.imread(filepath)`, while the right approach is `img = cv2.cvtColor(cv2.imread(filepath), cv2.COLOR_BGR2RGB)` as your current version.
I got the same scores as your mention now. Thanks again!
