### ISSUE TITLE
General query in MIRNet_model.py .

### ISSUE THREAD

**Issue by nan-rock** [swz30/MIRNet#17]
thanks for your great work sir!

I have one doubt in lines 296-297 of this file(MIRNet_model.py). 
 for j in range(self.height):
                blocks_out[j] = self.blocks[j][i](tmp[j])

Why have you used a for loop over here, according to the architecture as per my understanding, we could simply pass the temp(selective_kernel_fusion) output to the DAU(or blocks variable). I mean to say, couldn't we have just written, blocks_out[j] = self.blocks[j](tmp[j]). Kindly help.

**Comment by adityac8** [comment]
Hi @nan-rock 

Our `self.blocks` contains `DAU` in a 2D grid. Hence, we index them using `blocks_out[j] = self.blocks[j][i](tmp[j])`.
This gives us flexibility in case we want to increase our `height` or `width`.

Thanks
