### ISSUE TITLE
CUDA out of memory during own set of images.

### ISSUE THREAD

**Issue by joaocps** [swz30/MIRNet#18]
Hello @swz30 @adityac8  !

I made the necessary changes to the demo.py file present in the other repository in order to test MIRNet on my image set. During the process I had to make some configurations related to graphics compatibility, but everything was resolved.

However, at this moment I am faced with an error message:

`RuntimeError: CUDA out of memory. Tried to allocate 5.38 GiB (GPU 0; 3.95 GiB total capacity; 379.90 MiB already allocated; 2.89 GiB free; 16.10 MiB cached)`

Do you have any suggestions to solve my problem? I am using the pre-trained model provided, in a linux environment, with all the correct specifications with anaconda and graphics -> NVIDIA GEFORCE GTX 960m 4gb

Kind Regards,
João

**Comment by joaocps** [comment]
@adityac8 @swz30

**Comment by joaocps** [comment]
Same problem when running into google colab! 
@adityac8 @swz30

**Comment by adityac8** [comment]
Hi @joaocps 

Please refer to https://github.com/swz30/MPRNet/issues/32#issuecomment-826275971

Thanks
