### ISSUE TITLE
There is one issue.

### ISSUE THREAD

**Issue by koreadhkim** [swz30/MIRNet#3]
It prints the following error message. Can you comment on what's wrong?
I tried to do the Enhancement Task on my custom image.

![스크린샷 2020-08-13 오후 4 58 47](https://user-images.githubusercontent.com/48986889/90109087-428b4100-dd86-11ea-90c9-ab8126b2c7c6.png)

**Comment by adityac8** [comment]
Hi @koreadhkim 
Thank you for taking interest in our work.
For using a custom dataset, please make sure that the shape of images are in multiples of 8. If they are not, you can do the following modifications in `test_enhancement.py`.
Use `batch_size = 1`
```
# Pad the input
factor = 8
h,w = rgb_noisy.shape[2], rgb_noisy.shape[3]
H,W = ((h+factor)//factor)*factor, ((w+factor)//factor)*factor
padh = H-h if h%factor!=0 else 0
padw = W-w if w%factor!=0 else 0
rgb_noisy = F.pad(rgb_noisy, (0,padw,0,padh), 'reflect')
rgb_restored = model_restoration(rgb_noisy)
# Unpad the output
rgb_restored = rgb_restored[:,:,:h,:w]
```

**Comment by koreadhkim** [comment]
Wow! First of all, thanks for the quick reply, Thank you. 
Thank you for your awesome research. Could you please share the Training Code?
