### ISSUE TITLE
new issue

### ISSUE THREAD

**Issue by koreadhkim** [swz30/MIRNet#4]
Wow! First of all, thanks for the quick reply, Thank you.
Thank you for your awesome research. Could you please share the Training Code?

**Comment by tuvovan** [comment]
I made one myself here using TF-Keras. Not sure it is  same or not as I was not able to reach the PSNR value which is stated in the paper. Check it out here!

https://github.com/tuvovan/MIRNet---Keras

**Comment by adityac8** [comment]
The training code is now released.
