### ISSUE TITLE
A lightweight, fast and extended version of MIRNet is accepted in TPAMI

### ISSUE THREAD

**Issue by Devil-Ideal** [swz30/MIRNet#53]
hi! I'm very interested in your work, especially the lightweight version published in TPAMI. I would like to know the type of GPU used, and the total GPU memory  time required for MIRNETv2 training. I noticed that batchsize is 64 in MIRNETv2 but only 16 in MIRNET. MIRNETv2 uses a larger batchsize and patch, which means more GPU memory is required.

**Comment by adityac8** [comment]
You can have a look at the Table. MIRNetv2 uses less parameters and flops as MIRNet. We trained our models on 8 Tesla V100s. If you have a different GPU, you can adjust the batch size to run on your machine.
<img width="1300" alt="image" src="https://github.com/swz30/MIRNet/assets/19192257/0ad12088-015b-406f-b09c-f6c8be9e5b57">

**Comment by Devil-Ideal** [comment]
> You can have a look at the Table. MIRNetv2 uses less parameters and flops as MIRNet. We trained our models on 8 Tesla V100s. If you have a different GPU, you can adjust the batch size to run on your machine. <img alt="image" width="1300" src="https://user-images.githubusercontent.com/19192257/260313546-0ad12088-015b-406f-b09c-f6c8be9e5b57.png">

thank you for your reply
