### ISSUE TITLE
Processing for different upscaling factor

### ISSUE THREAD

**Issue by akineeic** [swz30/MIRNet#6]
Thanks for your wonderful sharing first! And I have a small question about how you handle different upscaling factors in the model for super resolution task, since I havn't found the description in the implementation details parts of your paper.

**Comment by adityac8** [comment]
Hi
The [RealSR](https://github.com/csjcai/RealSR) **version1** dataset proposed in ICCV 2019 have the same dimensions for LR and HR. Hence, we do not need to explicitly handle the upscaling factor.
In case you want to use our model for other datasets(where LR and HR have different resolutions), you could add this [module](https://github.com/yulunzhang/RCAN/blob/a57c5ed293b5ad9b64c1895d645f62d9a334fa11/RCAN_TestCode/code/model/common.py#L58) at the end of our network.
Thanks

**Comment by akineeic** [comment]
Thanks for your explanation!
