### ISSUE TITLE
I can train this model using one gpu?

### ISSUE THREAD

**Issue by AselSiriwardena** [swz30/MIRNet#7]
Hi, I have followed your which is awesome!
I wanted to train this model with some additional data. will it be possible to do it on a gtx 1660ti or a rtx 2060 laptop GPU?

I'm still a student. That's the best gpu I can afford right now.

Thanks!

**Comment by adityac8** [comment]
HI @AselSiriwardena 
Thank you for your interest in our work.
You can have a look at #5 for details on adjusting parameters, such as `batch_size` and `n_feat` for your GPU of 6GB memory.
Please note that changing these parameters would result in a trade-off between training time and performance.
Thanks

**Comment by AselSiriwardena** [comment]
Thank you so much for your reply! 
I have one more question. 
- In #5 you have mentioned that you used two NVIDIA Tesla V100 GPUs. are you using a cloud service?
