### ISSUE TITLE
number of parameters

### ISSUE THREAD

**Issue by tuvovan** [swz30/MIRNet#8]
Hi, thanks for your work.

Could you please share the number of parameter of your network?
I implemented it and it seems to have more than 34M params?

Thanks!

**Comment by adityac8** [comment]
Hi @tuvovan 
We use the following snippet to calculate the model parameters.
```
def params_count(model):
    """Computes the number of parameters."""
    return np.sum([p.numel() for p in model.parameters()]).item()
```
The number of parameters for our MIRNet model are 31.7 Million.
In case you want to have a lighter version, you can have a look at #5 for details on adjusting parameters, such as `batch_size` and `n_feat`.

Thanks
