### ISSUE TITLE
Issue With Processing real world images (not 600x400px) with LOL

### ISSUE THREAD

**Issue by ofirkris** [swz30/MIRNet#9]
Hello, well done!

How can I test on real world images with different resolutions? (example image attached)
When I try image enhancement on my own input images with different aspect ratio, nothing happens.
![sd image test](https://user-images.githubusercontent.com/9070477/99915698-e6817280-2d0d-11eb-89cc-d49a5ba44f75.jpg)

**Comment by tuvovan** [comment]
https://github.com/tuvovan/MIRNet---Keras

try this!
